---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
spec:
  chart:
    spec:
      chart: charts/latest/csi-driver-smb
      sourceRef:
        kind: GitRepository
        name: csi-driver-smb
  interval: 1h
  values:
    linux:
      enabled: true
    windows:
      enabled: false
    controller:
      runOnControlPlane: false
    priorityClassName: system-cluster-critical
