apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ys1CtPCr4Feuo/CGReTLpbeB5uEsd/Fd725G0JJSDCGQ3k36GNrxGg==,iv:C+Iy0l4iyj7//opwNfLCEvMu4VDN7Y2TFbmdgLeuwz0=,tag:RyuiaPQ8Vay0V7eQKI2a4w==,type:str]
sops:
  age:
    - recipient: age1yvqkwgsn76crld5vldn5eskh2zch8j8cqa7x3stq9d30cjxw2elsa9r09w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSjNlcGJrSDVQQWFyb0hS
        OGlWb2Z6d3BjeDNOY3dlbW0rMXh4ZFhJMG1BCmd6ZUJ2VEZYRmlGdmhzbUlJTjVI
        VGpWN3FDMk9yYlNRT2NFbDFGU3FsNTQKLS0tIFVXUGpIanlzUWhtNjdNWGpQSEtE
        RzJDa3BjVGJaMG0zZHZVS2h1a2srVDAK9u2uytY7HhjnYc1jKruKXGmFC8OQj2L6
        JKpuGBLo3Ij4J1fI/1eYNoTbi8A5l++5kG2hI6P8IKNdgP+rbNdSJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T23:42:48Z"
  mac: ENC[AES256_GCM,data:tyTxLxkgywyWlLipq48cxdaytZ9NRlPzQWgkv/4Dg0IdxgBpz7dfF2yHJpghf1Sz7hAXbvpZpILhhZOCbI5Nyu7bDGXLcX1hmjsGF+hnGpB98dabEpdbJd8Knm+AQhGFd1xITcI+oLqn7ys038voLzk0LWvhX9I/V8RIUUkc4/8=,iv:N/ojBb8PuFOk1HKqFkMYQZ/odq31vHH1MJO6P7qvv+0=,tag:1iQfR6GtmMX914zEYRo6mA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
