apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:vDFKSbz428lcLQAc1bz5liUErKo+LFWB4rRYaSwNByULb/JO3HnSWg==,iv:OOp2f6VJThPpQ4zqeL2by4Fmt1r/wRp0Zq7jjEuMpvs=,tag:OqWE3/o/juMBBvrBxR0VuQ==,type:str]
sops:
  age:
    - recipient: age1yvqkwgsn76crld5vldn5eskh2zch8j8cqa7x3stq9d30cjxw2elsa9r09w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZVhsTG80NGh1N0RMbUUw
        Tys3RktvQzFCSGp2Q1VxVm0wTEZoM3RySXgwCkR3UXFrWTcrWXdRT1V1bmowRUI3
        NnVsMmxkN1lFV1g0OWZBMyt0ZXlIT1EKLS0tIHpnbVFxQnNDMEN2MjlWRWRDOTk5
        VWNaOGJLWjdtcEd5MTdFMmhUektVOGcKKtIOptYmRvfwUFK2/ICQU7se5o2iiKLu
        mR9ZZBRo+bZ+8zYikQFfXp9gpCy3pscAnoAkHTH4kRm4FuPIrvyfTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T00:55:14Z"
  mac: ENC[AES256_GCM,data:yaFIkmZt33i2xFSg/W8uq8roigzQUmYB2eKKOYFc+zGSJ2K0S/OoMxMOGgB+fp6ShQxTZL5Y24ZLTEHMdRWnv2/bFtZvcmN9Fsf2ymgecHOIuedMSFqjKcmJJV3WyXDjyP22zw6Fkdx74DYL8Guckv1yhdkEFagXO/5xv2NnOyo=,iv:cAXE60WAfhqGniF02iO+e/6jyka4ZaasYJIg1yZN15w=,tag:r/A+axJoAJ4xRT1lL9hP6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
