apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3VKvDw9vXjI/,iv:h9NanYYzDToqdjUeXvw5x/BmulPbJT0nUagS8N/v5Bw=,tag:gEOkbOy/1eumAGHM7kKrcA==,type:str]
sops:
  age:
    - recipient: age1yvqkwgsn76crld5vldn5eskh2zch8j8cqa7x3stq9d30cjxw2elsa9r09w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMktjZkJNYjJQbjc2eTJm
        SGo4bXB1K2YyN1NJb0pGUUQ1b0EwUFJkT0VBCmxxeVoxZXI4TFdUb0dSK1VYK25I
        ZTRjdjIrendrYnRHVndkRUZTMDdSTk0KLS0tIHQvU3BWVmhYSldKRk5XR0p2MjF6
        djZvTUpCeGpqc2lOVVVrR3hNQStLemcK3hEX6gMY+9kbcrEkaKojOj6Fp8iRXtOs
        M06w14voKXLAipLi1C6Nl+VEJVUQBtIT3KPFhpalKeN9mhYucqeCIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T23:42:48Z"
  mac: ENC[AES256_GCM,data:Dv47iVRU1Hlg/v0gldHGpycBtSe8tV+jQRtcfqTxviUs0o9BRygtLcXGMUE467nA7lEL3Jn3MH52t0+krwMdnmSLun08PJfL4JJ4Ef4Rqg1rVOoHfQhQ4JKZNJHDdLZ3qDUIe4D/NMbVK4mCuSZbU3VeGRDWSJws8WAxLdR6rCc=,iv:XUonXaTZPPIS6qqVsYvMNE2nBQTazeGQKRZZqT9lUIk=,tag:B+Yw0cQzQtkq744e4m/jnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
