apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:dJUWREdSw4Fm,iv:as3YxVpxkZ6IBmoUz4AQA0q10P6AbMUgAuSUhpZFfdw=,tag:WBqVCuT5OdK0eG97KyRlOA==,type:str]
sops:
  age:
    - recipient: age1yvqkwgsn76crld5vldn5eskh2zch8j8cqa7x3stq9d30cjxw2elsa9r09w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIckRuTXhpZUVpM2hwZkh2
        UVYzRUt1c0lsWkZQcnRXeEZMZnliSXRHcTNJCktLOWNDT1AyTW1DTnkxdXNBNnFj
        aURvVFN0UmJaQmNUUTQrNlp3d1h4dW8KLS0tIEc0RVlqdjFxV0ZHSVRPeDJiQVZI
        UUU5VGtSeElsK1lPT2lkYjE0OGdacDQKZG1KG04eXruBd/qdjwLUpJLSqwfo7t/Z
        U/bgXd28X1yzKZK9U1po2dEcGZzCVSZKctDB4uoFpvf+DXeLE983sQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T00:55:14Z"
  mac: ENC[AES256_GCM,data:rayuTg7ooNGHByezMuaLnHflu2ZS6p85IJ8gUwn+Q/9V7xzbqn4S/9GQ5yaPdA/Il2NnIpibXnUdqZFuM6AwoyMkx/TA+2MxK+cEZixbVIWdrWMSsemhQCRSDkdqxnPDJks95kos4kkOOmTf56mwGmBAyEcJRI6b/JxCQTslPBc=,iv:hEQB4wKEFgvXW1SkbyDIVJ1FknwfWygr7LxKp8axoCQ=,tag:XGqe3gnCaDZZHgqOJldxIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
