apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:0Z2ZUzdB6fqJFDBCUMZhKK6JqsyRaEfTsAJQK8deLgA=,iv:CJuqNAH7bh6kB+GttgVuXHvhHvsn+Kpu91oDHiexU38=,tag:GN2ATVFgFWLSlRHM3BtJkA==,type:str]
sops:
  age:
    - recipient: age1yvqkwgsn76crld5vldn5eskh2zch8j8cqa7x3stq9d30cjxw2elsa9r09w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bWZnV3dyMjRSdml4NndT
        enJBRFZheUlWR08vNmhWNFpvMXR0dGVMSUNzCjc4WHIzTHBhQmtOR21xN3hkeEcx
        dWZ4TGcyTmpucFd6ZXBPWVFudDVnZ2cKLS0tIEs2Q1lUUEtKNVpxakw1MVZMZlp5
        eHJrSFhsaEtIY05RSEdrdDhuVFRhY1UK8ikJRUpccXLvczKM/RPlr9aPo9nnQhCR
        Dl1OFLXChR7QaP8d70nGhAX+geiqANGBJlDSzqJ4CYZ1YUJAg9+/cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T23:42:48Z"
  mac: ENC[AES256_GCM,data:Wt6H+BXmy7WGQCI+tTDbWHgB9pAGWwM5pCuQoPIT0FUSNWCqkUZuo6YKKfaDTk4BCqkEBQ2vtpRAPrLQW57CykdMiFhZya0pPtqANfNm2YHm1QEHriKp859LVEAooh5N5K4l2n6MXOcS2gF3XsqSRv9zVSBkxmtiotNQyTTdnQs=,iv:MNAygMjsHOkluqAiXrlh7in5s/INvcOAFhvJ7JqEchU=,tag:3kmFIVYT8ZKaHsWbACo03Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
