apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:T7ASqW/y3aaXHnxrvT7DftBS7iffY5AdZMfi396UQ6o=,iv:zl2Bjs5D7uR+dR5md25wt/l88nkzdWYxKcVVbVm11PQ=,tag:cVD6Da5gwnPsALMri41x5w==,type:str]
sops:
  age:
    - recipient: age1yvqkwgsn76crld5vldn5eskh2zch8j8cqa7x3stq9d30cjxw2elsa9r09w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VDFWTXlybXZ2U1VsVVUw
        Y2VIbTAxUVVKTkJsRWxKOWZ1aUNwVW9wMG1JCjk0aGRsbitWWlQ2NWNBOG9WRTND
        WVZjQmF1M2gwT1RjWnVha3RXNEpCRUEKLS0tIDNJWHdxZEVqek83cGJBb1RKVXFp
        aE1oanVlM00wL3pQaFNPY04vYVd0MFEKvKOW7YbnuzbGGm5w7r2SCsWIqD2nJkza
        5yJVeFFdSKcPPKMABWeOyUzRJVuOLmQPxMQuG5fkFboP6/EX8IBO6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T00:55:15Z"
  mac: ENC[AES256_GCM,data:LOANdmMFJLw3jdZLGiDFd3XcVJnJWGJZNHwrFA6mwP2XuwWZLlKD7eHPTn80YRZtoTm9wmT28rJiNcZkrQvOi3ERWRsINA5g4Mr5W4AnNtr6QzF4Gu+8UGn0hCy3s58js9ghV+C8scAOObhhY3O/XsN3cDL7OJDdIBrzeGuw610=,iv:mnYaEIZ3VmhnMaLRxH8lv6p16CsRO0h/f0QoQFXWjbQ=,tag:X3yCpAcLtc5jDjSRN0Rzrw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
