apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ISjSgnmozWw0Hf9tv0Ae1bJIomYisaaF6topURETnh2zSLrp1gvIBrPCpoae5y8eVB/RSVZ5hjeMrKmZOzIRPUgqu/FXgQPjdZTJhoM4HD8IxFe83bJ0GbwogkF/Uo7QeZ1KLG28WLQ1UTvdcwINw0Ikf+mwP7TZJKZM5gWHRfhxXdYzOjca+g/CGqyLTXtOW72L8VIwkSDDHZlELbkALb0c6dHLa2sZrvJVqte9PVCxPy7R,iv:j0+I0d/i1N3upd8IczXinLewEV6Ve4aJJqtiEg/bE+E=,tag:NwqVbvH1USRnnp3hf/Bz2g==,type:str]
sops:
  age:
    - recipient: age1yvqkwgsn76crld5vldn5eskh2zch8j8cqa7x3stq9d30cjxw2elsa9r09w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUkJQc2t5UXdIMDVtdGxy
        aSt6VW1KNkRiTDEzT2JoV2NwckNHejZNK3ljCmcwSDdoN0dEQ0ZPL3JZWmk0ck5D
        aHJOeVhCRlVJNGtrOHVVSUdJSStqdEEKLS0tIDdUUUFFaXgvcExsclo4TnQxYzJZ
        bFI4bHFSRGxPc0daS3JwV0FvQS9wWFUKGlJpuhAdQLHIwnb3VTUjM8rVn7NV9tiC
        47S5V7kDIR51zwPwylYxkKKr1H8dm5xPpG2y3749NeUr3XXzsoRWhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T23:42:48Z"
  mac: ENC[AES256_GCM,data:PRZtYWFiI23/Pl3TNg8crkVwle4Tvtxf2lKIhvVOwzFyC3LOp1W9t3vqxi55HVQMcwSvkmeATHaXUUEVnVRAd80PKnFIZu6+6L+KmDoTwyE1/ZSEzzhn3vOrjN6dirpc1L4OPB9CkwzDUOD/IfVjW1YQnTgBtshiS4OuONTvaJg=,iv:t376iZteQp/Q/GvXlk2gTqqkpJ6gICmiD6W8qtf1Umk=,tag:BGhnAtrfdAs1camjTUViRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
