apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:BfNi1c3+t7iMhQJm97oyChp1qOOadwsBmfAe64a1/msYNxSnvcSV2YrXTLdjmAoMAykhuyexknsPi4tNB4slAt9+umXa/twOpsCy4SvnIqmQWFO6Nbk2j/Uj0VLJ6YB0ABGv6tkRssZ1zWTtiSIfOFAZDOqCs1U6qQawjWXZtIrVYLdvOsuwAR8P7eY7IN5/ovarNLUyxTkPoF1c+iyJE0vyUBok6MO6pQdI2DGEK4l8nzaq,iv:z3r0wo+MxzGh1Me9TQFhkXoxGq4VOdVLYRSngvBwQDI=,tag:e3bg2t06AEurJ+uyUiG1bg==,type:str]
sops:
  age:
    - recipient: age1yvqkwgsn76crld5vldn5eskh2zch8j8cqa7x3stq9d30cjxw2elsa9r09w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZWhoMU1NUVJyUlRaRWNl
        QXhzbzhXU1BxZlA5S01ocVVHSXgzSTJLT1NBCnRoZkJpbE5wSmI4TXQzS2NydTJv
        VGVlNFJOUHJjVXJSTFVEWmliOU9oUWsKLS0tIDI1N2tveVJvT05YL0J4THFBeUt1
        SGJGbkNtUmlIdzRwZjZYZkRPVm5xNlkK7ALheITdKAZ1ZJIlml5kxOt4zMgG5ipL
        8obwxl9r+xr81oOADamutspWvyDVE7DvdKFfdH3/q6u+cI/QP1s+tQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T00:55:14Z"
  mac: ENC[AES256_GCM,data:XKXelyBV93ScifekqEPHy5kP68WdKisHk7OhzJiql1XQdglptq+rNLbL0CaRR42DMka3s+xveWWzTo9XKHZrGtkprNv+LuCzKCYmeBo10hGdH+PoM2WbxMmjLNscMEQZ5V4/eHyZG+AUWeD+VXGhdpyxdxBI1kfD0cA3IJFdQvk=,iv:0xjCWINUo3V+iOPmzFvMkZldtmRVnSKvkYVo3N3y/HI=,tag:fQA298SgqwdfcNKt8iD6zg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
