apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:3jD329YwfaZFBx10hz3VoVQhirF8uLyakMQdrtkUanXvPh3R0MVvJQ==,iv:mYkMch5ex90gR5i98oeI1PRlvJhiIGVD0ccW0A+ER9o=,tag:F7mbRs9fDxcLlZ1dm+Zwcg==,type:str]
sops:
  age:
    - recipient: age1yvqkwgsn76crld5vldn5eskh2zch8j8cqa7x3stq9d30cjxw2elsa9r09w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TWZjblRadGxYdE1pcFJt
        V2hrc3VDRUhqUTBVK2k2eDhvaGtHTzJBN2lvCkZsNWxmUDR2ZFVoSjh5UGEwVVJV
        RGFucGh0TXhTVEVCd2VnL1BGUXJSYkkKLS0tIDhlN3JpUjMydm0vOFpPbjRReUNz
        c1Rnazk1dnJRcUM5cmhaZ3JNYzNtSG8KRwhWymK8gnoH1Jwn02K7O9gy9sUOd6Rk
        Q42wslhGocYy7lcWSmT7/TYYO/DwIn988JaixXSWJd9dRPoKnALmTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T23:42:48Z"
  mac: ENC[AES256_GCM,data:a1PF5mowDjN3ULi12zCSdb924K/3t+GZUxO6xgs95GnCMVsCS408+FNCafPH98Epe3krrLvGOw7zDqpR9DS3HG3SwelZbrRDavJykAaNKC0dWHoXdSZ4L4AICcDV9NmhRv8cyDBeflAhm82I8AjUVZQsFypLE60Cvq8F52mNXWA=,iv:kK0+87RSESAejiVnpQeawEUh8fTdE7CrGrwSF0yxkiU=,tag:HRroLr3TTbVM7xyIWvQtqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
