apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:SJAqWuAeWKo7NvAwOjwgVXN2NSJWje78eU4CHf4onKeyPjfBb9POKg==,iv:uRZs7JpRfrvRvVsaS+U79xcMw+c+k5cklRqCyRBU9gA=,tag:bgBUIpdEyGy/6aZ1qmD4vQ==,type:str]
sops:
  age:
    - recipient: age1yvqkwgsn76crld5vldn5eskh2zch8j8cqa7x3stq9d30cjxw2elsa9r09w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbWpmWlZkU2k3VFVmTG9r
        MW5tWUxNK0xqTmVMTSszY1Vnd21Hb3pzSkRVCnIydk9GQXpxdnRPaFhGTWhNRW9l
        Y3BydUJWNmU1bm95N3BJRS84SWNsdEEKLS0tIEdVcHpWNFBjUWxwelZqZTBxRzQ0
        dkg3U29sZWUvY2puL2ZsTERNbnF1SmMKaJNFHlOMbTJGUrQdKGSAGsejYaVXw15a
        nB52F4hHw+v6xe2TvqfK3QHKaGhDZe3PD+rPkdnePlOnutcVasoH9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T00:55:14Z"
  mac: ENC[AES256_GCM,data:U/ZnCoeHWfYLGrJK7kN4Xu457Ng4qqMfVen21UBojG2ozof0JIzPnPDGCM2jIYXyW1bK1Bmu+h35NQNr/LCLsvDTEKYGNqpkfZ7K8zbNJLA28GFRbbLKvMzwzlZVkNdq12kBz8u+U3Xpq9zM7X0h1krQF26u+39OmqqrDXDiPFI=,iv:KOkwC3tU7LFsWhEJTKnKPnLU81IsWRcGJbSF1z2exLQ=,tag:yHLbUO6OhCZrRuZeJP84Ig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
